version: "3.9"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.39.0
    container_name: jaeger
    restart: unless-stopped
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"
      - "4318:4318"

  # db:
  #   image: postgres:15.1-alpine
  #   container_name: db
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_PASSWORD: 6f20bf78714ea12e283ad1df68b8f4f1
  #     POSTGRES_USER: finz
  #     POSTGRES_DB: finz
  #     PGUSER: finz
  #   ports:
  #     - "5432:5432"
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
