type Category {
  id: ID!
  name: String!
  color: String
  createdAt: DateTime!
  updatedAt: DateTime!
}

type Query {
  category(id: ID!): Category! @auth(requires: USER)
  categories: [Category!]! @auth(requires: USER)
}

input CategoryInput {
  name: String!
  color: String
}

type Mutation {
  createCategory(input: CategoryInput!): Category! @auth(requires: USER)
  updateCategory(id: ID!, input: CategoryInput!): Category! @auth
  deleteCategory(id: ID!): Void @auth
}
