enum TransactionKind {
  INCOME
  EXPENSE
  TRANSFER
}

type Transaction {
  id: ID!
  name: String!
  amount: BigInt!
  date: Date!
  kind: TransactionKind!
  createdAt: DateTime!
  updatedAt: DateTime!
  category: Category!
}

type Query {
  transaction(id: ID!): Transaction! @auth(requires: USER)
  transactions: [Transaction!]! @auth(requires: USER)
}

input TransactionInput {
  name: String!
  amount: BigInt!
  date: Date!
  kind: TransactionKind!
  categoryId: ID!
}

type Mutation {
  createTransaction(input: TransactionInput!): Transaction! @auth(requires: USER)
  updateTransaction(id: ID!, input: TransactionInput!): Transaction! @auth(requires: USER)
  deleteTransaction(id: ID!): Void @auth(requires: USER)
}
